apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cron-demo
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid #Allow, Forbid, Replace
  successfulJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            repo: N/A
        spec:
          containers:
          - name: cron-demo
            image: mzavaletav/democont:1.3
            imagePullPolicy: IfNotPresent
          restartPolicy: Never
