apiVersion: apps/v1
kind: Deployment
metadata:
  name:  democontainer
spec:
  selector:
    matchLabels:
      app: democontainer
  replicas: 1
  template:
    metadata:
      labels:
        app:  democontainer
    spec:
      containers:
      - name:  democontainer
        image:  mzavaletav/democontainer:1.1