apiVersion: v1
kind: Service
metadata:
  name: apidemo
spec:
  type: ClusterIP
  selector:
    app: apidemo
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  apidemo
  labels:
    app:  apidemo
spec:
  selector:
    matchLabels:
      app: apidemo
  replicas: 1
  template:
    metadata:
      labels:
        app:  apidemo
    spec:
      containers:
      - name:  apidemo
        image:  mzavaletav/demoapi:2.0
        ports:
        - containerPort:  8080
          name:  apidemo
---
apiVersion: v1
kind: Service
metadata:
  name: apidemo-nodeport
spec:
  type: NodePort
  selector:
    app: apidemo
  ports:
    - port: 8080
      targetPort: 8080