apiVersion: apps/v1
kind: Deployment
metadata:
  name:  democlient
  labels:
    app:  democlient
spec:
  selector:
    matchLabels:
      app: democlient
  replicas: 1
  template:
    metadata:
      labels:
        app:  democlient
    spec:
      containers:
      - name:  democlient
        image:  mzavaletav/democlient:2.0
        env:
        - name: URL
          value: http://10.20.12.162:31033